const path = require('path')
const Fontmin = require('fontmin')
const text = require('../data/constellations.json')
  .map(([name]) => name)
  .join('')
new Fontmin()
  .src(path.resolve(__dirname, 'yomogifont-TTF/yomogifont.ttf'))
  .dest(__dirname)
  .use(Fontmin.glyph({ text }))
  .run(err => err && console.error(err))
